version: '3'
networks:
    frontend:
        driver: bridge
services:
    uwsgi:
        container_name: road_websrv
        image: road:1.0
        ports:
            - 6001:6001
        restart: always
        networks:
            - frontend
        volumes:
            - {path/to/nas/image/folder}:{mount/point/in/container}
        environment:
            - RD_DB_HOST={DBHOST}
            - RD_DB_USER={DBUSER}
            - RD_DB_PASSWORD={DBPASSWORD}
            - RD_DB_DATABASE={DBNAME}
            - RD_IMG_PATH={mount/point/in/container}