version: '3'
networks:
    frontend:
        driver: bridge
services:
    uwsgi:
        container_name: road_websrv
        image: road:1.0
        ports:
            - 6001:6001
        restart: always
        networks:
            - frontend
        volumes:
            - /road/road_defects/web:/road/road_defects/web